### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by t0-0** [floatingbigcat/mm_builder#10]
```
Traceback (most recent call last):
  File "/home/mm_builder/py_workers/wiki2itl.py", line 144, in <module>
    main()
  File "/home/mm_builder/py_workers/wiki2itl.py", line 136, in main
    df = wiki2itl(input_file=args.input,patterns=patterns)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mm_builder/py_workers/wiki2itl.py", line 112, in wiki2itl
    item = dewiki(item)
           ^^^^^^^^^^^^
  File "/home/mm_builder/py_workers/wiki2itl.py", line 57, in dewiki
    text = wtp.parse(text).plain_text()  # wiki to plaintext 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.pyenv/versions/mm_builder/lib/python3.11/site-packages/wikitextparser/_wikitext.py", line 732, in plain_text
    lst[b] = replace_tables(
             ^^^^^^^^^^^^^^^
  File "/home/.pyenv/versions/mm_builder/lib/python3.11/site-packages/wikitextparser/_wikitext.py", line 177, in _table_to_text
    widths = [0] * len(data[0])
                       ~~~~^^^
IndexError: list index out of range
```

this error is occurred when item is the following text.

```
250px|流山線の路線図]]
| map_state = 
}}
{| {{Railway line header}}
{{UKrail-header|停車場・施設・接続路線|}}
{{BS-table}}
{{BS4|BHF|O1=HUBaq|STR|O2=HUBq|KBHFa|O3=HUBeq||0.0|RN1 [[馬橋駅]]||}}
{{BS4|STR|ABZgl|KRZu|STR+r||||}}
{{BS6||O1=HUBrg|HST|O2=HUBeq|STR|STR|STR||||[[新松戸駅]]||}}
{{BS6|HSTq|O1=HUBe|KRZh|KRZh|KRZh|KRZh|ABZq+l|||←[[東日本旅客鉄道|JR東]]：[[武蔵野線]]→|}}
{{BS6||STR|STR|BHF|ABZl+l|STRr|1.7|RN2 [[幸谷駅]]|}}
{{BS4|STR|ABZg+l|KRZu|STRr|}}
{{BS4|STRr|STR|STR||||←JR東：[[常磐緩行線]]||}}
{{BS4|STRq|STRr|STR||||←JR東：[[常磐快速線]]||}}
{{BS4|||eBHF||2.2|''[[大谷口駅]]''|-1953|}}
{{BS4|||BHF||2.8|RN3 [[小金城趾駅]]|}}
{{BS4|||WBRÜCKE1||||[[坂川]]}}
{{BS4|||BHF||3.6|RN4 [[鰭ヶ崎駅]]|}}
{{BS4||tSTRq|KRZt|tSTRq|||←[[首都圏新都市鉄道]]：|}}
{{BS4|||STR|||||[[首都圏新都市鉄道つくばエクスプレス|つくばエクスプレス]]→|}}
{{BS4|||BHF||5.1|RN5 [[平和台駅 (千葉県)|平和台駅]]|}}
{{BS4|||KBHFe||5.7|RN6 [[流山駅]]|}}
|}
|}
<!-- 画像 -->
```

**Comment by floatingsun** [comment]
These content works good for dewiki function from my side and ouputs:
'250px|流山線の路線図]] | map_state = }} {| |} |} '

Maybe this is not the exact text that inputted into this dewiki funciton?

**Comment by t0-0** [comment]
```
dewiki("""
250px|流山線の路線図]]
| map_state = 
}}
{| {{Railway line header}}
{{UKrail-header|停車場・施設・接続路線|}}
{{BS-table}}
{{BS4|BHF|O1=HUBaq|STR|O2=HUBq|KBHFa|O3=HUBeq||0.0|RN1 [[馬橋駅]]||}}
{{BS4|STR|ABZgl|KRZu|STR+r||||}}
{{BS6||O1=HUBrg|HST|O2=HUBeq|STR|STR|STR||||[[新松戸駅]]||}}
{{BS6|HSTq|O1=HUBe|KRZh|KRZh|KRZh|KRZh|ABZq+l|||←[[東日本旅客鉄道|JR東]]：[[武蔵野線]]→|}}
{{BS6||STR|STR|BHF|ABZl+l|STRr|1.7|RN2 [[幸谷駅]]|}}
{{BS4|STR|ABZg+l|KRZu|STRr|}}
{{BS4|STRr|STR|STR||||←JR東：[[常磐緩行線]]||}}
{{BS4|STRq|STRr|STR||||←JR東：[[常磐快速線]]||}}
{{BS4|||eBHF||2.2|''[[大谷口駅]]''|-1953|}}
{{BS4|||BHF||2.8|RN3 [[小金城趾駅]]|}}
{{BS4|||WBRÜCKE1||||[[坂川]]}}
{{BS4|||BHF||3.6|RN4 [[鰭ヶ崎駅]]|}}
{{BS4||tSTRq|KRZt|tSTRq|||←[[首都圏新都市鉄道]]：|}}
{{BS4|||STR|||||[[首都圏新都市鉄道つくばエクスプレス|つくばエクスプレス]]→|}}
{{BS4|||BHF||5.1|RN5 [[平和台駅 (千葉県)|平和台駅]]|}}
{{BS4|||KBHFe||5.7|RN6 [[流山駅]]|}}
|}
|}
<!-- 画像 -->
""")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in dewiki
  File "/home/.pyenv/versions/mm_builder/lib/python3.11/site-packages/wikitextparser/_wikitext.py", line 732, in plain_text
    lst[b] = replace_tables(
             ^^^^^^^^^^^^^^^
  File "/home/.pyenv/versions/mm_builder/lib/python3.11/site-packages/wikitextparser/_wikitext.py", line 177, in _table_to_text
    widths = [0] * len(data[0])
                       ~~~~^^^
IndexError: list index out of range
```
I got this error.
