### ISSUE TITLE
'NoneType' object has no attribute 'start'

### ISSUE THREAD

**Issue by t0-0** [floatingbigcat/mm_builder#9]
```
Traceback (most recent call last):
  File "/home/mm_builder/py_workers/wiki2itl.py", line 140, in <module>
    main()
  File "/home/mm_builder/py_workers/wiki2itl.py", line 132, in main
    df = wiki2itl(input_file=args.input,patterns=patterns)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mm_builder/py_workers/wiki2itl.py", line 108, in wiki2itl
    item = dewiki(item)
           ^^^^^^^^^^^^
  File "/home/mm_builder/py_workers/wiki2itl.py", line 57, in dewiki
    text = wtp.parse(text).plain_text()  # wiki to plaintext 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.pyenv/versions/mm_builder/lib/python3.11/site-packages/wikitextparser/_wikitext.py", line 732, in plain_text
    lst[b] = replace_tables(
             ^^^^^^^^^^^^^^^
  File "/home/.pyenv/versions/mm_builder/lib/python3.11/site-packages/wikitextparser/_wikitext.py", line 175, in _table_to_text
    for row in t.data()
               ^^^^^^^^
  File "/home/.pyenv/versions/mm_builder/lib/python3.11/site-packages/wikitextparser/_table.py", line 159, in data
    match_table = self._match_table
                  ^^^^^^^^^^^^^^^^^
  File "/home/.pyenv/versions/mm_builder/lib/python3.11/site-packages/wikitextparser/_table.py", line 135, in _match_table
    pos = FIRST_NON_CAPTION_LINE(table_shadow, pos).start()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'start'
```

this error is occurred when item is the following text.

```

thumb|450px|left|北海道の地方自治体の人口増加率分布図。2015年度と2020年度国勢調査から算出した。
{{Multicol}}
'''増加'''
{{legend|#44AA00|7.5 - 10.0 %}}
{{legend|#66FF00|5.0 - 7.5 %}}
{{legend|#99FF55|2.5 - 5.0 %}}
{{legend|#CCFFAA|0.0 - 2.5 %}}
{{Multicol-break}}
'''減少'''
{{Legend|#FFAAAA|0.0 - 2.5 %}}
{{Legend|#FF5555|2.5 - 5.0 %}}
{{Legend|#FF0000|5.0 - 7.5 %}}
{{Legend|#AA0000|7.5 - 10.0 %}}
{{Legend|#550000|10.0 % 以上}}
{{Multicol-end}}]]
{{人口統計|code=01000|name=北海道|image=Demography Hokkaidou.svg}}

===主要都市===
北海道は他の多くの都府県と比べて主要都市部に人口が偏在するという傾向が強く、特に<!--2011年時点で-->近年は札幌市への人口集中が著しく、道内の他の自治体を大きく圧倒し、2番目の人口規模をもつ旭川市でさえ札幌市の人口の6分の1程度しかない。道内の179の自治体のうち[[政令指定都市]]は札幌市の1市、[[中核市]]は[[旭川市]]と[[函館市]]の2市で、[[特例市|施行時特例市]]は存在しない。
:
人口の都市集中は、他の市町村の人口密度がさらに低いことを意味する。家屋の密度が著しく低く、大区画でほぼ無人の畑地・牧草地が広がる大地を、どこまでも続く直線道路が切っていく景観は、人口密度の低さで北海道につぐ東北地方でも見られない、北海道独特のものである<ref name="新日本地誌ゼミナール『北海道地方』2頁。この箇所の執筆は古川史郎。"/>。[[2022年]]（令和4年）現在で179の自治体のうち、およそ83%に上る149の自治体が[[過疎地域]]に指定されている<ref>{{Cite web|url=https://www.pref.hokkaido.lg.jp/fs/5/6/8/8/4/4/5/_/%E2%98%86%E5%9C%B0%E5%9F%9F%E6%8C%87%E5%AE%9A%E7%8A%B6%E6%B3%81(R4.4.1%E7%8F%BE%E5%9C%A8)220310(%E6%BA%B6%E3%81%91%E8%BE%BC%E3%81%BF).pdf|title=地域指定一覧　道内の過疎、辺地、山村、離島、特豪地帯等の指定状況|publisher=北海道|format=PDF|accessdate=2022-06-13}}</ref>。

;北海道の主要都市を掲載する。
{| class="infobox" style="text-align:center; width:100%; margin-right:10px; font-size:100%"
! colspan="10" style="background:#e9e9e9; padding:0.3em; line-height:1.2em;"| '''北海道地方の主要都市'''
|-
!rowspan=30|
[[File:SapporoCity Skylines2020.jpg|150px]]<br /><small>[[札幌市]]</small><br />[[File:Skyline of Asahikawa City.jpg|150px]]<br /><small>[[旭川市]]</small><br />
! style="text-align:center; background:#f5f5f5;"| <small>#</small>
! style="text-align:left; background:#f5f5f5;"| 都市名
! style="text-align:left; background:#f5f5f5;"| 地域名
! style="text-align:center; background:#f5f5f5;"| 人口
! style="text-align:center; background:#f5f5f5;"| <small>#</small>
! style="text-align:left; background:#f5f5f5;"| 都市名
! style="text-align:left; background:#f5f5f5;"| 地域名
! style="text-align:center; background:#f5f5f5;"| 人口
!rowspan=21|
```

**Comment by floatingsun** [comment]
This also shows that
[[File:SapporoCity Skylines2020.jpg|150px]] is not catched in ja, japanese wiki really have a mixture use of different format. Not so sure if it is the same case for others.

**Comment by t0-0** [comment]
Wow, that's certainly true. We need to change this as well.

**Comment by t0-0** [comment]
Then there may be less need for separate patterns for each language.

**Comment by floatingsun** [comment]
make sense, Has changed this in this PR
https://github.com/floatingbigcat/mm_builder/pull/11/

**Comment by floatingsun** [comment]
After this, these content actually works from the latest master

**Comment by t0-0** [comment]
```
dewiki("""
thumb|450px|left|北海道の地方自治体の人口増加率分布図。2015年度と2020年度国勢調査から算出した。
{{Multicol}}
'''増加'''
{{legend|#44AA00|7.5 - 10.0 %}}
{{legend|#66FF00|5.0 - 7.5 %}}
{{legend|#99FF55|2.5 - 5.0 %}}
{{legend|#CCFFAA|0.0 - 2.5 %}}
{{Multicol-break}}
'''減少'''
{{Legend|#FFAAAA|0.0 - 2.5 %}}
{{Legend|#FF5555|2.5 - 5.0 %}}
{{Legend|#FF0000|5.0 - 7.5 %}}
{{Legend|#AA0000|7.5 - 10.0 %}}
{{Legend|#550000|10.0 % 以上}}
{{Multicol-end}}]]
{{人口統計|code=01000|name=北海道|image=Demography Hokkaidou.svg}}

===主要都市===
北海道は他の多くの都府県と比べて主要都市部に人口が偏在するという傾向が強く、特に<!--2011年時点で-->近年は札幌市への人口集中が著しく、道内の他の自治体を大きく圧倒し、2番目の人口規模をもつ旭川市でさえ札幌市の人口の6分の1程度しかない。道内の179の自治体のうち[[政令指定都市]]は札幌市の1市、[[中核市]]は[[旭川市]]と[[函館市]]の2市で、[[特例市|施行時特例市]]は存在しない。
:
人口の都市集中は、他の市町村の人口密度がさらに低いことを意味する。家屋の密度が著しく低く、大区画でほぼ無人の畑地・牧草地が広がる大地を、どこまでも続く直線道路が切っていく景観は、人口密度の低さで北海道につぐ東北地方でも見られない、北海道独特のものである<ref name="新日本地誌ゼミナール『北海道地方』2頁。この箇所の執筆は古川史郎。"/>。[[2022年]]（令和4年）現在で179の自治体のうち、およそ83%に上る149の自治体が[[過疎地域]]に指定されている<ref>{{Cite web|url=https://www.pref.hokkaido.lg.jp/fs/5/6/8/8/4/4/5/_/%E2%98%86%E5%9C%B0%E5%9F%9F%E6%8C%87%E5%AE%9A%E7%8A%B6%E6%B3%81(R4.4.1%E7%8F%BE%E5%9C%A8)220310(%E6%BA%B6%E3%81%91%E8%BE%BC%E3%81%BF).pdf|title=地域指定一覧　道内の過疎、辺地、山村、離島、特豪地帯等の指定状況|publisher=北海道|format=PDF|accessdate=2022-06-13}}</ref>。

;北海道の主要都市を掲載する。
{| class="infobox" style="text-align:center; width:100%; margin-right:10px; font-size:100%"
! colspan="10" style="background:#e9e9e9; padding:0.3em; line-height:1.2em;"| '''北海道地方の主要都市'''
|-
!rowspan=30|
""")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in dewiki
  File "/home/.pyenv/versions/mm_builder/lib/python3.11/site-packages/wikitextparser/_wikitext.py", line 732, in plain_text
    lst[b] = replace_tables(
             ^^^^^^^^^^^^^^^
  File "/home/.pyenv/versions/mm_builder/lib/python3.11/site-packages/wikitextparser/_wikitext.py", line 175, in _table_to_text
    for row in t.data()
               ^^^^^^^^
  File "/home/.pyenv/versions/mm_builder/lib/python3.11/site-packages/wikitextparser/_table.py", line 159, in data
    match_table = self._match_table
                  ^^^^^^^^^^^^^^^^^
  File "/home/.pyenv/versions/mm_builder/lib/python3.11/site-packages/wikitextparser/_table.py", line 135, in _match_table
    pos = FIRST_NON_CAPTION_LINE(table_shadow, pos).start()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'start'
```
I got this error.
